# Generated by Django 4.2.4 on 2023-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecord',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
